### ISSUE TITLE
router: some ideas for improvement

### ISSUE THREAD

**Issue by RussellLuo** [asynkron/protoactor-go#153]
### 1. [Interface](https://github.com/AsynkronIT/protoactor-go/blob/dev/router/router.go#L5-L10)

It's more intuitive to rename it to `Router` as follows:

```go
// Interface -> Router
type Router interface {
	// maybe renaming this to `Route` is better?
	RouteMessage(message interface{}, sender *actor.PID)
	SetRoutees(routees *actor.PIDSet)
	GetRoutees() *actor.PIDSet
}
```

### 2. [config.go](https://github.com/AsynkronIT/protoactor-go/blob/dev/router/config.go)

router and router-config should be differentiated from each other, so it may be more suitable and more concise to do the following renamings:

**RouterConfig**

```go
// RouterConfig -> Config
type Config interface {
	RouterType() RouterType
	OnStarted(context actor.Context, props *actor.Props, router Router)
	// CreateRouterState -> CreateRouter
	CreateRouter() Router
}
```

**GroupRouter**

```go
// GroupRouter -> GroupConfig
type GroupConfig struct {
	Routees *actor.PIDSet
}
```

**PoolRouter**

```go
// PoolRouter -> PoolConfig
type PoolConfig struct {
	PoolSize int
}
```

### 3. [process](https://github.com/AsynkronIT/protoactor-go/blob/dev/router/process.go#L12-L18)

router and router-actor should be differentiated from each other:

```go
type process struct {
	// router -> routerActor
	routerActor   *actor.PID
	// state -> router
	router    Router
	mu       sync.Mutex
	watchers actor.PIDSet
	stopping int32
}
```

### 4. Routers with different routing strategies

Take [broadcast router](https://github.com/AsynkronIT/protoactor-go/blob/dev/router/broadcast_router.go) for example, the refactored version looks like this: 

```go
package router

import "github.com/AsynkronIT/protoactor-go/actor"

// broadcastGroupRouter -> broadcastGroupConfig
type broadcastGroupConfig struct {
	// GroupRouter -> GroupConfig
	GroupConfig
}

// broadcastPoolRouter -> broadcastPoolConfig
type broadcastPoolConfig struct {
	// PoolRouter -> PoolConfig
	PoolConfig
}

// broadcastRouterState -> broadcastRouter
type broadcastRouter struct {
	routees *actor.PIDSet
}

func (router *broadcastRouter) SetRoutees(routees *actor.PIDSet) {
	router.routees = routees
}

func (router *broadcastRouter) GetRoutees() *actor.PIDSet {
	return router.routees
}

func (router *broadcastRouter) RouteMessage(message interface{}, sender *actor.PID) {
	router.routees.ForEach(func(i int, pid actor.PID) {
		pid.Request(message, sender)
	})
}

func NewBroadcastPool(size int) *actor.Props {
	return actor.FromSpawnFunc(spawner(&broadcastPoolConfig{PoolConfig{PoolSize: size}}))
}

func NewBroadcastGroup(routees ...*actor.PID) *actor.Props {
	return actor.FromSpawnFunc(spawner(&broadcastGroupConfig{GroupConfig{Routees: actor.NewPIDSet(routees...)}}))
}

func (config *broadcastPoolConfig) CreateRouter() Router {
	return &broadcastRouter{}
}

func (config *broadcastGroupConfig) CreateRouter() Router {
	return &broadcastRouter{}
}
```

## Remove Props from group router

To follow [the similar improvement on protoactor-dotnet](https://github.com/AsynkronIT/protoactor-dotnet/issues/242), some possible changes are:

### 1. [groupRouterActor](https://github.com/AsynkronIT/protoactor-go/blob/dev/router/routeractor_group.go#L9-L14)

Remove the `props` field:

```go
type groupRouterActor struct {
	config RouterConfig
	// state -> router
	router  Router
	wg     sync.WaitGroup
}

func (a *groupRouterActor) Receive(context actor.Context) {
	switch m := context.Message().(type) {
	case *actor.Started:
		// a.props -> nil
		a.config.OnStarted(context, nil, a.state)
		a.wg.Done()

	...
}
```

### 2. [spawn](https://github.com/AsynkronIT/protoactor-go/blob/dev/router/spawn.go#L7)

Refactor the `spawn` function like this:

```go
package router

import (
	"github.com/AsynkronIT/protoactor-go/actor"
)

func spawn(id string, config Config, props *actor.Props, parent *actor.PID) (*actor.PID, error) {
	ref := &process{}
	proxy, absent := actor.ProcessRegistry.Add(ref, id)
	if !absent {
		return proxy, actor.ErrNameExists
	}

	ref.router = config.CreateRouter()

	if config.RouterType() == GroupRouterType {
		ra := &groupRouterActor{
			config: config,
			router:  ref.router,
		}
		ra.wg.Add(1)
		ref.router, _ = actor.DefaultSpawner(id+"/router", actor.FromInstance(ra), parent)
		ra.wg.Wait() // wait for routerActor to start
	} else {
		var pc = *props
		pc.WithSpawnFunc(nil)
		ra := &poolRouterActor{
			props:  &pc,
			config: config,
			router:  ref.router,
		}
		ra.wg.Add(1)
		ref.router, _ = actor.DefaultSpawner(id+"/router", actor.FromInstance(ra), parent)
		ra.wg.Wait() // wait for routerActor to start
	}

	return proxy, nil
}
```

Or maybe we should split `spawn` into two functions:

```go
func spawnGroup(id string, config Config, parent *actor.PID) (*actor.PID, error) {}

func spawnPool(id string, config Config, props *actor.Props, parent *actor.PID) (*actor.PID, error) {}
```

and the corresponding `spawner` should be splitted:

```go
func groupSpawner(config Config) actor.SpawnFunc {
	return func(id string, props *actor.Props, parent *actor.PID) (*actor.PID, error) {
		return spawnGroup(id, config, parent)
	}
}

func poolSpawner(config Config) actor.SpawnFunc {
	return func(id string, props *actor.Props, parent *actor.PID) (*actor.PID, error) {
		return spawnPool(id, config, props, parent)
	}
}
```

**Comment by RussellLuo** [comment]
@AsynkronIT/developers any thoughts?

**Comment by rogeralsing** [comment]
I like the gist of it, but I would like to keep it closer to the new implementation of the Kotlin and C# versions.

In those, we have moved the spawner func into the Config object, like so:
https://github.com/AsynkronIT/protoactor-kotlin/blob/master/proto-router/src/main/kotlin/actor/proto/router/RouterConfig.kt

The RouterConfig now returns a Props with the router spawner assigned.

This means that the code to spin up new routers become very simple:
https://github.com/AsynkronIT/protoactor-kotlin/blob/master/proto-router/src/main/kotlin/actor/proto/router/Router.kt
it simply delegates the call into creating a router config and returning its props.

This way, we don't need to have different implementations for router and pool configs, the config contains everything that is needed and can then spawn all routers in the same way.

Thoughts?

**Comment by RussellLuo** [comment]
The new implementation looks great!

I have another question, according to [Akka documentation](http://doc.akka.io/docs/akka/snapshot/scala/routing.html#a-router-actor):

> - Group - The routee actors are created externally to the router and the router sends messages to the specified path using actor selection, **without watching for termination**.

But the [GroupRouterConfig](https://github.com/AsynkronIT/protoactor-kotlin/blob/master/proto-router/src/main/kotlin/actor/proto/router/GroupRouterConfig.kt#L7) still watches its routees:

```
routees.forEach { context.watch(it) }
```

What is the consideration?

**Comment by rogeralsing** [comment]
that's an oversight from us. we should remove that.

**Comment by RussellLuo** [comment]
If I am not mistaken, I think both the current Go implementation (e.g. [broadcastRouterState](https://github.com/AsynkronIT/protoactor-go/blob/dev/router/broadcast_router.go#L13-L29)) and the current Kotlin implementation (e.g. [BroadcastRouterState](https://github.com/AsynkronIT/protoactor-kotlin/blob/master/proto-router/src/main/kotlin/actor/proto/router/BroadcastRouterState.kt#L7-L17)) have concurrency-safety problem.

Because `AddRoutee`/`RemoveRoutee` messages (sent by the router actor, in one goroutine) and `RouteMessage` operation (occurs within any other external actor, which uses the router to distribute its work, in another goroutine) will happen concurrently, but there is no synchronization primitive used to protect the getting/setting operation of `routees` property.

In [Akka implementation](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/routing/RoutedActorCell.scala#L48-L49), `volatile` is used to protect the internal `_router` property.

**Comment by raskolnikoov** [comment]
Den 31 juli 2017 10:07 fm skrev "Luo Peng" <notifications@github.com>:

**Comment by bryanpkc** [comment]
On x86 at least, the `SetRoutees` call atomically replaces the `*PIDSet` in `broadcastRouterState`, `randomRouterState` and `roundRobinState`, so the problem is not too bad. I have fixed the code for `consistentHashRouterState` and can submit a pull request.

**Comment by bryanpkc** [comment]
Oh wait, never mind. The `consistentHashRouterState` fix was already merged into the dev branch; I was looking at the wrong branch (master).

**Comment by alex023** [comment]
@rogeralsing 
I thought it was a very good improvement proposal, especially the project documentation and  remarks were very few cases.

**Comment by cpx86** [comment]
@RussellLuo If we're thinking the same thing, for Kotlin that should have been fixed in https://github.com/AsynkronIT/protoactor-kotlin/pull/7. Is that what you mean?

The issue still exists in Go and dotnet though... Right @rogeralsing? :)

**Comment by RussellLuo** [comment]
@cpx86 I'm not familiar with Kotlin and dotnet.

But as far as I know, Go's specification does not provide any atomicity guarantee on scalar values (including pointers) without synchronization primitives, although the current implementation on specific platforms (e.g. x86) do provide atomicity.

See https://github.com/golang/go/issues/16048 for details.

**Comment by bryanpkc** [comment]
@RussellLuo You're right. The current way of writing a pointer in `SetRoutees` is not strictly correct on x86 either because the write may not be visible on other cores consistently. To be correct, we'd need to use import `sync/atomic` and `unsafe`, and call `atomic.StorePointer` instead. This will end up going through a couple of calls (that are not inlined), and executing an XCHG instruction instead of a MOV instruction. The XCHG instruction is a memory barrier on X86, making the write a volatile write. However, the extra calls and the import of `unsafe` seem rather drastic to me.
