### ISSUE TITLE
The server the server continues to report errors , after the client node is closed, 

### ISSUE THREAD

**Issue by alex023** [asynkron/protoactor-go#235]
I write a simple client/server, accroding to "example/chat" message, and found that using **context.Respond** triggers a problem:
## client.go
```
func main() {
	remote.Start("127.0.0.1:0")
	server := actor.NewPID("127.0.0.1:8080", "chatserver")
	props := actor.FromFunc(func(context actor.Context) {
		switch msg := context.Message().(type) {
		case *messages.Connected:
			log.Println(msg.Message)
		}
	})
	client := actor.Spawn(props)
	server.Request(&messages.Connect{
		Sender: client,
	}, client)
	time.Sleep(5*time.Second)
	client.Stop()
	time.Sleep(3*time.Second)
}
```
## server.go
```
func main() {
	remote.Start("127.0.0.1:8080")
	props := actor.FromFunc(func(ctx actor.Context) {
		switch msg := ctx.Message().(type) {
		case *messages.Connect:
			log.Printf("Client %v connected", msg.Sender)
			time.Sleep(3 * time.Second)
			//note use Respond method
			ctx.Respond(&messages.Connected{Message: "Welcome!"})
		}
	})
	actor.SpawnNamed(props, "chatserver")
	console.ReadLine()
}
```
when client closed,the server will output:
```
2018/04/27 15:15:38 [REMOTE] EndpointReader failed to read error="rpc error: code = Canceled desc = context canceled" 
2018/04/27 15:15:38 [REMOTE] EndpointWriter lost connection to address address="127.0.0.1:55130" error="rpc error: code = Unavailable desc = transport is closing" 
2018/04/27 15:15:38 [REMOTE] EndpointWatcher handling terminated address="127.0.0.1:55130" 
2018/04/27 15:15:38 [REMOTE] [ACTOR] Recovering actor="127.0.0.1:8080/EndpointSupervisor/$3" reason="interface conversion: interface {} is *remote.EndpointTerminatedEvent, not *remote.remoteDeliver" stacktrace="vendor/github.com/AsynkronIT/protoactor-go/remote.(*endpointWriter).sendEnvelopes:94" 
2018/04/27 15:15:38 [REMOTE] Started EndpointWriter address="127.0.0.1:55130" 
2018/04/27 15:15:38 [REMOTE] EndpointWriter connecting address="127.0.0.1:55130" 
2018/04/27 15:15:38 [REMOTE] EndpointWriter failed to connect address="127.0.0.1:55130" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:55130: connect: connection refused\"" 
2018/04/27 15:15:40 [REMOTE] [ACTOR] Recovering actor="127.0.0.1:8080/EndpointSupervisor/$3" reason="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:55130: connect: connection refused\"" stacktrace="vendor/github.com/AsynkronIT/protoactor-go/remote.(*endpointWriter).initialize:37" 
2018/04/27 15:15:40 [REMOTE] Started EndpointWriter address="127.0.0.1:55130" 
2018/04/27 15:15:40 [REMOTE] EndpointWriter connecting address="127.0.0.1:55130" 
2018/04/27 15:15:40 [REMOTE] EndpointWriter failed to connect address="127.0.0.1:55130" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:55130: connect: connection refused\"" 
2018/04/27 15:15:42 [REMOTE] [ACTOR] Recovering actor="127.0.0.1:8080/EndpointSupervisor/$3" reason="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:55130: connect: connection refused\"" stacktrace="vendor/github.com/AsynkronIT/protoactor-go/remote.(*endpointWriter).initialize:37" 
2018/04/27 15:15:42 [REMOTE] Started EndpointWriter address="127.0.0.1:55130" 
2018/04/27 15:15:42 [REMOTE] EndpointWriter connecting address="127.0.0.1:55130" 
2018/04/27 15:15:42 [REMOTE] EndpointWriter failed to connect address="127.0.0.1:55130" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:55130: connect: connection refused\"" 
```
I think  EndpointSupervisor  recovering is meaningless when the client is disconnected.

**Comment by alex023** [comment]
maybe,**endpointSupervisor.HandleFailure** should invoke **StopChildren**
```
func (state *endpointSupervisor) HandleFailure(supervisor actor.Supervisor, child *actor.PID, rs *actor.RestartStatistics, reason interface{}, message interface{}) {
	supervisor.RestartChildren(child)
        //supervisor.StopChildren(child)
}
```

**Comment by chriskolenko** [comment]
Is there a work around for this currently?

**Comment by alex023** [comment]
This problem has not been followed up recently. You can test or just use protoactor locally to avoid this problem， through message middleware（such Nats etc.） between nodes.

**Comment by PotterDai** [comment]
@alex023 Hmm, this is really strange. Please do go update on protoactor package since this issue is not about reconnecting and error handling, but about type conversion between EndpointTerminatedEvent and RemoveDeliver,

> 2018/04/27 15:15:38 [REMOTE] [ACTOR] Recovering actor="127.0.0.1:8080/EndpointSupervisor/$3" reason="interface conversion: interface {} is *remote.EndpointTerminatedEvent, not *remote.remoteDeliver" stacktrace="vendor/github.com/AsynkronIT/protoactor-go/remote.(*endpointWriter).sendEnvelopes:94" 

which should be addressed in previous PRs.
currently it's handled like this:
https://github.com/AsynkronIT/protoactor-go/blob/dev/remote/endpoint_writer.go#L96

@chriskolenko Could you post your error log? Thank you very much! = )

**Comment by Strum355** [comment]
Getting the same error but without `interface conversion: interface {} is *remote.EndpointTerminatedEvent, not *remote.remoteDeliver`. End up in a loop of `cluster.[REMOTE] - [ACTOR] Recovering`, Starting EndpointWriter, trying to connect and then fails. 

> maybe,**endpointSupervisor.HandleFailure** should invoke **StopChildren**
> 
> ```
> func (state *endpointSupervisor) HandleFailure(supervisor actor.Supervisor, child *actor.PID, rs *actor.RestartStatistics, reason interface{}, message interface{}) {
> 	supervisor.RestartChildren(child)
>         //supervisor.StopChildren(child)
> }
> ```

This didnt solve it
